### ISSUE TITLE
Installation Information in README.md differs from the official Install Guide

### ISSUE THREAD

**Issue by bmack** [TYPO3/TYPO3.CMS.BaseDistribution#10]
See:

https://docs.typo3.org/typo3cms/InstallationGuide/QuickInstall/Composer/Index.html

**Comment by Countryen** [comment]
+1
Also just tried the install command here and didn't work
`composer create-project typo3/cms-base-distribution project-name ^9`

Message:
 [InvalidArgumentException]
 Could not find package typo3/cms-base-distribution with version 9.

**Comment by Countryen** [comment]
Adding this because it's the same topic:
When you run it with ` --non-interactive`  it tells you that it's deprecated and you need to use `--no-interaction` instead.
_"Option --non-interactive is deprecated. Please use --no-interaction instead."_

**Comment by helhum** [comment]
> Also just tried the install command here and didn't work

Any hints how to reproduce?

```bash
$ composer create-project typo3/cms-base-distribution project-name ^9
Installing typo3/cms-base-distribution (v9.5.0)
  - Installing typo3/cms-base-distribution (v9.5.0): Loading from cache
Created project in project-name
...
```

This works flawlessly for me.

**Comment by helhum** [comment]
> When you run it with --non-interactive it tells you that it's deprecated

That is an easy change. @Countryen can you create a pull request to fix this?

**Comment by Countryen** [comment]
> Any hints how to reproduce?

On Windows x64 with WAMP.
I run: `composer create-project typo3/cms-base-distribution HULM ^9` in PowerShell.

And result is a red box saying: 
_[InvalidArgumentException]
Could not find package typo3/cms-base-distribution with version 9._

Okay I guess it doesn't read the "^" part of the version correctly when using PowerShell.
Follwing works: 
`composer create-project typo3/cms-base-distribution HULM ~9`
`composer create-project typo3/cms-base-distribution HULM 9.5`

But command `composer create-project typo3/cms-base-distribution HULM` works fine, too.

Just recently installed wamp + composer + everything for typo3 dev so everything should be up to date and "default".

**php -v:** PHP 7.2.10 (cli) (built: Sep 13 2018 00:48:27) ( ZTS MSVC15 (Visual C++ 2017) x64 )
**composer --version:**  Composer version 1.7.2 2018-08-16 16:57:12
**PSVersion:** 5.1.17763.1

**Comment by gilbertsoft** [comment]
Had the same exception as above with ddev see #19 Using ^9.5 as version solved the issue

**Comment by helhum** [comment]
See: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/pull/19#issuecomment-530409648
