### ISSUE TITLE
Not possible to package new version 9 LTS of TYPO3 Core

### ISSUE THREAD

**Issue by bmack** [TYPO3/TYPO3.CMS.BaseDistribution#11]
It is currently not possible to put the TYPO3.CMS.BaseDistribution in the release process to update this repository automatically during release, due to the inclusion of TYPO3 Console, where there is no roadmap or information when a v9 LTS-compatible version is going to be available.

This brings us in a very uncomfortable situation when we release, as we recommend on get.typo3.org that people should use composer and the base distribution.

**Comment by helhum** [comment]
Feel free to remove TYPO3 Console as dependency, to ease the release process. 

I would have loved to release a new version upfront, but since last minute changes broke the package in the past (a seemingly minor change a few day ago broke it again), the only reliable point in time to release a compatible version is **after** the core has been tagged.

**Comment by bmack** [comment]
Hmm, in an ideal world, we'd need to:
Step 1: Tag TYPO3 Core with the new version + subtree packages tagging
Step 2: Update + Tag typo3/minimal
Step 2: Update + Tag TYPO3 Console with compatibility for new version
Step 3: Update + Tag Base Distribution with compatibility for new core and console version

We only have step 1 automated, step 2 _should_ be possible to integrate, but for step 3 and 4 we'd need integration tests to see if it works before doing the update+tag process.

Do you have an estimate when TYPO3 Console will be compatible for TYPO3 v9.5? I'm reluctant to do bigger changes on the base distribution now (it's release day) and just looked at the situation and did some tests early this morning.

**Comment by helhum** [comment]
> Do you have an estimate when TYPO3 Console will be compatible for TYPO3 v9.5?

If [this](https://github.com/TYPO3-Console/TYPO3-Console/pull/754) goes well, I'd tag a new version in a couple of hours, marking it as compatible with 9.5.*@dev, which will ensure compatibility with a released 9.5.0.

There are some other implications, that should tackled, but this can be done in a bugfix release.

**Comment by bmack** [comment]
k. thx. I will take care of typo3/minimal then.

**Comment by helhum** [comment]
Release process of TYPO3 Console started. Have to wait for Appveyor to catch up, but other than that it'll be ready in a couple of minutes.

**Comment by helhum** [comment]
I tagged a new version
