### ISSUE TITLE
typo3 folder is placed in public/ instead of vendor/typo3 - bug or feature?

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3/TYPO3.CMS.BaseDistribution#15]
Note: 
The documentation at https://docs.typo3.org/typo3cms/InstallationGuide/MigrateToComposer/MigrationSteps.html still mentions to add `"cms-package-dir": "{$vendor-dir}/typo3/cms",` when upgrading.

Is this no longer recommended for fresh installs (and upgrades)? 
If so: Why not?

Should `"cms-package-dir": "{$vendor-dir}/typo3/cms",` be applied to `cms-base-distribution`, or should the `cms-package-dir` configuration be removed from the migration guide? 
One of the two must be wrong.

I would wish for some documentation about the rationale behind moving directories around. I do understand that we want as much source as possible in `vendor/` (outside `public/` or whatever `$web-dir` you pick) and that we do need the `typo3/index.php` for TYPO3 backend entry. 

I also understand that placing `typo3/` in vendor and using a symlink might not improve things dramatically, since the web server would follow the symlink and any vulnerability within `typo3/` would still be exposed. ( _Is this the answer to "why are you dropping `cms-package-dir`"?_ )

However, why cannot all of `typo3/` (especially `sysext/`) be moved into `vendor/` - except for the entry point(s)? This would probably require a build step to collect necessary assets into `typo3temp/assets/`, which makes it sound like a future project.

**Comment by helhum** [comment]
For reference:
https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/103

And the discussion https://github.com/TYPO3/CmsComposerInstallers/issues/75, which should tackle everything on the why and how the future might look like.
