### ISSUE TITLE
helhum/typo3-console missing in 10.x and master Branches

### ISSUE THREAD

**Issue by tbal** [TYPO3/TYPO3.CMS.BaseDistribution#20]
The documentation still shows usages of typo3cms, but unlike to previous branch versions (e.g. 9.x and 8.x) the package helhum/typo3-console is not required in composer.json.

Didn't created a pull request, because I'm unsure about the correct version constraints.

**Comment by helhum** [comment]
That is the case because TYPO3 Console does not support TYPO3 10 yet.

**Comment by gilbertsoft** [comment]
Since the release of TYPO3 Console 6.0.0 this issue is fixed and could be closed imho.
