### ISSUE TITLE
ext:lowlevel is not installed

### ISSUE THREAD

**Issue by josefglatz** [TYPO3/TYPO3.CMS.BaseDistribution#25]

**Comment by gilbertsoft** [comment]
The idea of the base dist is not deliver all core extensions but a set of mostly used extensions to get a running TYPO3 instance. So IMHO this is just fine.
Feel free to add for you missing after running composer create-project. BTW in such cases where you want to add more extensions / packages it could make sense to use the --no-install option with composer create-project and require.

**Comment by gilbertsoft** [comment]
@josefglatz can we close this issue or do you think it's still valid?

**Comment by gilbertsoft** [comment]
@josefglatz just had another idea: we could require ext:lowlevel as dev dependency. That's what I'm also doing with the Bootstrap Package because I often need it for debugging.
@helhum what do you think?

**Comment by infabo** [comment]
> all core extensions but a set of mostly used extensions to get a running TYPO3 instance

* ext:dashboard https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/main/composer.json#L21
* ext:webhooks https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/main/composer.json#L41

These are probably not needed to run TYPO3 and are not commonly used either.

On the other hand:

* ext:lowlevel - refindex update/check is **essential** and having the `Configuration BE module` is quite nice and probably 9/10 TYPO3 integrators/developers use this module.
* ext:scheduler - having scheduled tasks configured is essential for most TYPO3 installations. there are some very important tasks that need to be run.
