### ISSUE TITLE
Define composer package type

### ISSUE THREAD

**Issue by t3easy** [TYPO3/TYPO3.CMS.BaseDistribution#38]
If the type is set to project, packagist will show a `composer create-project` snippet instead of `composer require`.

https://getcomposer.org/doc/04-schema.md#type
https://packagist.org/packages/typo3/cms-base-distribution
https://packagist.org/packages/moodle/moodle

**Comment by bmack** [comment]
@t3easy like this one? https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/pull/37

**Comment by t3easy** [comment]
Yes. Sorry have not seen this.

**Comment by bmack** [comment]
All good, feel free to vote for the PR.

**Comment by t3easy** [comment]
Duplicate of #37
