### ISSUE TITLE
Broken release/tag 10.4.2 - pointing to *@dev instead of stable core packages 

### ISSUE THREAD

**Issue by jpmschuler** [TYPO3/TYPO3.CMS.BaseDistribution#50]
10.4.2 was released to roll out the many changes made https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/compare/v10.4.1...v10.4.2
However during that the dependency to core packages was switched from stable to dev.
Thus a typical `composer create-project typo3/cms-base-distribution typo3 ^10` now installs the `*@dev` versions instead of the stable releases that where installed with 10.4.1.

Probably this is not intended.

**Comment by ohader** [comment]
What a mess... unfortunately this all is still a manual process... I'll revert those tags and do the magic

**Comment by ohader** [comment]
I am wondering why `~10.3.0` is shown in the diff - [`v10.4.1`](https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/v10.4.1/composer.json) correctly contained `^10.4`. Strange...

**Comment by ohader** [comment]
Are these `@dev@` versions required at all? For instance the `11.x` branch did not contain them.

**Comment by gilbertsoft** [comment]
Yes, they are required but pending change from my side like discussed last week.

**Comment by ohader** [comment]
Created a new `v10.4.3` tag using https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/v10.4.3/composer.json
@jpmschuler can you please confirm things work again on your side?

**Comment by jpmschuler** [comment]
Everything as expected, thanks!

**Comment by hoermannklaus** [comment]
Thanks for the quick fix. Works just fine.
