### ISSUE TITLE
Example command for unattended setup fails

### ISSUE THREAD

**Issue by pixelbrackets** [TYPO3/TYPO3.CMS.BaseDistribution#56]
**What did I do?** 

* Run the command given in the README to execute an unattended setup:

```bash
composer exec typo3cms install:setup --no-interaction --database-user-name=typo3 […]
```

**What did I expect?**

* Unattended setup runs fine, green checkboxes all the way

**What happened instead?**

* Composer throws an error message

```bash
>                                                    
> The "--database-user-name" option does not exist.  
>
> exec [-l|--list] [--] [<binary> [<args>...]]
```

**Proposed solution**

* Composer expects that the given arguments refer to the composer binary and does not pass them along to the triggered typo3cms binary 
* To pass the arguments to the typo3cms binary the use needs to make use of the [command argument separator](https://github.com/composer/composer/issues/10376)

**Comment by bmack** [comment]
Solved in main branch, v12 and v11
