### ISSUE TITLE
Version 12.4 needs "typo3/cms-lowlevel"

### ISSUE THREAD

**Issue by ochorocho** [TYPO3/TYPO3.CMS.BaseDistribution#59]
During install this errors is thrown:

```
(1/1) Symfony\Component\DependencyInjection\Exception\RuntimeException

Invalid service "lowlevel.configuration.module.provider.webhooks": class "TYPO3\CMS\Lowlevel\ConfigurationModuleProvider\AbstractProvider" not found while loading "TYPO3\CMS\Webhooks\ConfigurationModuleProvider\WebhookTypesProvider".
```

`composer req typo3/cms-lowlevel` fixed this issue.

**Comment by ohader** [comment]
Thanks! This also has been reported for TYPO3 core components at

* https://forge.typo3.org/issues/100844
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/79004

**Comment by ohader** [comment]
Thus, the issue still would exist without using the base distro (and still not having `typo3/cms-lowlevel` as local composer requirement). However, I'd be totally fine to add `typo3/cms-lowlevel` into base distro as well.

**Comment by sypets** [comment]
@ohader If https://review.typo3.org/c/Packages/TYPO3.CMS/+/79004 is not merged soon (and a release created), can you add typo3/cms-lowlevel to base distri? I think it will cause no harm and would make "first contact" with TYPO3 a little smoother.

**Comment by ohader** [comment]
It is merged and the next v12 release will be published on June 13, 2023.
