### ISSUE TITLE
Clearing cache doesn't work on an expired session but the platform doesn't shows this

### ISSUE THREAD

**Issue by pfpdev** [TYPO3/TYPO3.CMS.BaseDistribution#60]
On a Plesk 11.5.30, when clearing all cache when the session has expired:
- it looks like it's working but it actually doesn't 
- no error message is displayed
- behind the scenes, you can see a redirect to login page, but nothing happens in the browser

_Clear cache -> Flush all caches_
<img width="1602" alt="image" src="https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/assets/34255431/afcf8eba-7e22-4437-b8d8-f744b9c14268">

Requests happening behind the scenes
<img width="1608" alt="image" src="https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/assets/34255431/3c41e2ea-8ed0-4c82-bb7f-cf84abdadcfe">
<img width="1607" alt="image" src="https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/assets/34255431/13f10f7f-6786-418a-ba53-3d3d108667cc">

**Comment by bnf** [comment]
Thanks a lot for your report. We track issues on https://forge.typo3.org/projects/typo3cms-core

I've copied your issue into a bug report in there: https://forge.typo3.org/issues/105314
