### ISSUE TITLE
Remove doctrine/dbal 4.0.0-RC2 dependency

### ISSUE THREAD

**Issue by ohader** [TYPO3/TYPO3.CMS.BaseDistribution#65]
https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/v13.0.2/composer.json#L17

→ Doctrine DBAL v4.0.0 (stable) has been released
→ https://github.com/doctrine/dbal/releases/tag/4.0.0

**Comment by bnf** [comment]
Done with https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/commit/95deb0834b48f91ac26d80ab822f3509dd2ef2f2
