### ISSUE TITLE
Incorrect version constraints used in composer.json

### ISSUE THREAD

**Issue by rfay** [TYPO3/TYPO3.CMS.BaseDistribution#8]
The various releases of this project use incorrect version constraints in composer.json, making it impossible to test an earlier version.

For example, `composer create-project typo3/cms-base-distribution mytypo3 =9.2.1`  will *say* it's installing 9.2.1, but in fact it installs 9.3.1 (currently) (see [gist](https://gist.github.com/rfay/13bb893b91da22c5105928cf272f3d24)

If you look at the [9.x version of composer.json](https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/9.x/composer.json) you'll see that all the constraints say something like `		"typo3/minimal": "^9.3",`, which means they'll work *today*, but they won't work correctly when 9.4 comes around, because they'll pull in 9.4.

**Comment by helhum** [comment]
That was done pretty much on purpose, but I agree this can be confusing.
For 9 this does not make sense to be changed any more, so we might go a different way for 10
